server:
  port: 8081

jwt:
  secret: my-ultra-secure-secret-key-1234567890
  expiration:
    ms: 86400000

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:8083/event_organization
    username: event_user
    password: event_password
    pool:
      enabled: true

logging:
  level:
    root: INFO
    ru.eventorg: TRACE
    org:
      springframework:
        data:
          r2dbc: DEBUG
        web:
          filter: TRACE
          client: TRACE
          server: TRACE
          reactive: TRACE
        security: TRACE
